server:
  port: 8084

spring:
  cloud:
    config:
      server:
        git:
          uri: C:\Users\Gabriel\Documents\Gabriel\microservices-staging\file-config-server
          default-label: master
